### ISSUE TITLE
Inconsistency between manipulation and feedback messages

### ISSUE THREAD

**Issue by ghost** [trebb/pipeglade#1]
The manipulation commands that accept booleans (for example, `set_active`) use `0` and `1` as parameters, but feedback messages (for example, `toggled`) sends `off` and `on`.

Is there a reason for this? Should the API be changed so it's either one or the other for both manipulation and feedback?

**Comment by trebb** [comment]
You're probably right; the current solution looks a bit like numeric I/O in INTERCAL.

I guess the input should continue to resemble GTK's input, but the output could be changed easily.  I'll turn it into 0 and 1 in the next release.
